CREATE TABLE ACCOUNT(
ACCOUNT_ID INT PRIMARY KEY NOT NULL,
BALANCE INT NOT NULL
);

CREATE TABLE POSITION(
POSITION_ID SERIAL PRIMARY KEY NOT NULL,
OWNER_ID INT REFERENCES ACCOUNT(ACCOUNT_ID),
SYM VARCHAR(20) NOT NULL,
SHARE DOUBLE PRECISION NOT NULL
);

CREATE TABLE ORDERS(
ORDER_ID SERIAL PRIMARY KEY NOT NULL,
ACCOUNT_ID INT REFERENCES ACCOUNT(ACCOUNT_ID),
SYM VARCHAR(20) NOT NULL,
OPEN BOOLEAN NOT NULL DEFAULT TRUE,
PRICE INT NOT NULL,
SELL BOOLEAN NOT NULL,
TOTAL DOUBLE PRECISION NOT NULL,
REST DOUBLE PRECISION NOT NULL
);

CREATE TABLE EXECUTE(
EXECUTE_ID SERIAL PRIMARY KEY NOT NULL,
ORDER_ID INT REFERENCES ORDERS(ORDER_ID),
SHARE DOUBLE PRECISION NOT NULL,
PRICE INT NOT NULL,
TIME INT NOT NULL
);

