INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE) VALUES (1,100000);
INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE) VALUES (2,100000);
INSERT INTO ACCOUNT(ACCOUNT_ID, BALANCE) VALUES (3,100000);
INSERT INTO POSITION(OWNER_ID,SYM,SHARE) VALUES(1,'BIT',1000);
INSERT INTO POSITION(OWNER_ID,SYM,SHARE) VALUES(2,'BIT',1000);
INSERT INTO POSITION(OWNER_ID,SYM,SHARE) VALUES(3,'BIT',1000);
INSERT INTO POSITION(OWNER_ID,SYM,SHARE) VALUES(1,'USD',1000);
INSERT INTO POSITION(OWNER_ID,SYM,SHARE) VALUES(2,'USD',1000);
INSERT INTO POSITION(OWNER_ID,SYM,SHARE) VALUES(3,'USD',1000);
